### ISSUE TITLE
Python Bash GUI error.

### ISSUE THREAD

**Issue by LeWarEnds** [scorelab/OpenSNA#23] opened 2018-10-27 13:09 UTC
When the file is run, the bash crashes and get closed with a error related to Print Function.
As the environment is not implemented that good, it is recommended to do so like JAVA_ENVIRONMENT for Cassandra.
Also while running the Python GUI file, the Bash didn't load correctly and closes with no error. 
There should be something like error prompt.

Code : 

// like make it linked with the window or provide a specific environment to run the batch file.
if(enviromentSetup != windowEnviroment){
       cout << "Fatal Error. Install the Required Enviroment to run." << endl;
       return true;
       int timeError = default_random_engine randomGenerator(time(NULL));  // There should be some 
       range with which the comparison should be made 
       // as the error typecast should be an integer then the range should also be in integer
       uniform_int_distribution (int) randomError(// Range goes here);
}
else{
       return false;
       return 0; // closes the application when the generated number does not match the 
       enviromentSetup.
}

 Also please add more instruction to read me.

**Comment by malithsen** [comment] 2018-11-20 02:29
This is because the project uses python2 and you're most likely to run it with python3. I will close this as it's a duplicate of #8. Perhaps you could help with migrating from python2 to 3

**Closed by malithsen** 2018-11-20 02:29 UTC
